### PR TITLE
Typescript migration

### PR DESCRIPTION
**Pull request by beawar**
@zovomat @nubsthead @geeky-abhishek please check that your last changes done in devel are reported here in the right way.

@ all: if you think multiple pr are easier to review instead of this gigantic one, I will close this and open a pr for each component. Let me know.

### CODE REVIEW

**Comment by CataldoMazzilli** [comment]
Screenshot from 2022-05-03 17-03-45

update Button background prop

**Comment by CataldoMazzilli** [comment]
Screenshot from 2022-05-03 17-26-12

In LoadMore doc the List component use wrong prop factory

**Comment by CataldoMazzilli** [comment]
Screenshot from 2022-05-03 17-36-08

overflowTooltip is not a TextWithTooltip prop(is a prop of tooltip(and its description could be improved))

**Comment by CataldoMazzilli** [comment]
Screenshot from 2022-05-03 17-42-55

Last alignment example of container missmatch the description

**Comment by CataldoMazzilli** [comment]
Screenshot from 2022-05-03 17-47-05

add missing      width: '10px'   to show the inner div

**Comment by CataldoMazzilli** [comment]
Screenshot from 2022-05-03 18-20-44

<IconButton icon="Pricetags" onClick={click} {...iconButtonProps} /> 

this component in iconButton doc seems to be broken

**Comment by beawar** [comment]
> update Button background prop

Done


> overflowTooltip is not a TextWithTooltip prop(is a prop of tooltip(and its description could be improved))


What do you mean with description could be improved? Do you refer to TextWithTooltip component or to the overflowTooltip prop of Tooltip?

> In LoadMore doc the List component use wrong prop factory

Removed the example because it was wrong the usage of the List. If necessary, a better example could be add later

> Last alignment example of container missmatch the description

Updated the description of alignments

> add missing width: '10px' to show the inner div

Done

> this component in iconButton doc seems to be broken

Fixed by setting medium as default for size prop

**Review by zovomat — APPROVED** [review]

**Review by nubsthead — APPROVED** [review]

**Review by CataldoMazzilli — APPROVED** [review]

**Pull request merged**
